pipeline {
    agent any

    environment {
        SSH_CREDENTIALS = credentials('devops-key')
        DOCKERFILE = credentials('gitstats-dockerfile')
        BUCKET_NAME = 'gitstats.lientech.com.br'

        REPOSITORY_PREFIX = 'git@ssh.dev.azure.com:v3/lds-ifce/Lientech_ITGuys'

        REPOSITORY_NAME_FRONTEND = 'front-end'
        REPOSITORY_NAME_BACKEND = 'back-end'
        REPOSITORY_NAME_CHATBOT = 'chatbot'
        REPOSITORY_NAME_CLASSIFIER = 'classifier-service'
        REPOSITORY_NAME_RANKING = 'candidate-ranking'

    }

    stages {
        stage('Creating Dockerfile') {
            steps {
                sh 'cat ${DOCKERFILE} > ./Dockerfile'
            }
        }
        stage('Iosi') {
            parallel {
                stage('front-end') {
                    stages {
                        stage('Building front-end image') {
                            steps {
                                sh '''docker build  --build-arg REPO=${REPOSITORY_PREFIX}/${REPOSITORY_NAME_FRONTEND} \
                                --build-arg REPO_NAME=${REPOSITORY_NAME_FRONTEND} --build-arg SSH_PRV_KEY="$(cat ${SSH_CREDENTIALS})" \
                                --build-arg BRANCH=develop . -t gitstats-image:${REPOSITORY_NAME_FRONTEND}
                                '''
                            }
                        }
                        stage('Copying stats from container') {
                            steps {
                                sh '''docker run --name ${REPOSITORY_NAME_FRONTEND} -d gitstats-image:${REPOSITORY_NAME_FRONTEND} tail -f /dev/null && \
                                mkdir -p ${REPOSITORY_NAME_FRONTEND} && docker cp ${REPOSITORY_NAME_FRONTEND}:/stats ./${REPOSITORY_NAME_FRONTEND}
                                '''
                            }
                        }
                        stage('S3 cleanup and upload stats') {
                            steps {
                                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'profile-lientech-aws']]) {
                                    sh 'aws s3 rm s3://${BUCKET_NAME}/${REPOSITORY_NAME_FRONTEND}/* --recursive'
                                    sh 'aws s3 cp ./${REPOSITORY_NAME_FRONTEND} s3://${BUCKET_NAME}/${REPOSITORY_NAME_FRONTEND} --recursive'
                                }
                            }
                        }
                    }
                }
                stage('back-end') {
                    stages {
                        stage('Building back-end image') {
                            steps {
                                sh '''docker build  --build-arg REPO=${REPOSITORY_PREFIX}/${REPOSITORY_NAME_BACKEND} \
                                --build-arg REPO_NAME=${REPOSITORY_NAME_BACKEND} --build-arg SSH_PRV_KEY="$(cat ${SSH_CREDENTIALS})" \
                                --build-arg BRANCH=develop . -t gitstats-image:${REPOSITORY_NAME_BACKEND}
                                '''
                            }
                        }
                        stage('Copying stats from container') {
                            steps {
                                sh '''docker run --name ${REPOSITORY_NAME_BACKEND} -d gitstats-image:${REPOSITORY_NAME_BACKEND} tail -f /dev/null && \
                                mkdir -p ${REPOSITORY_NAME_BACKEND} && docker cp ${REPOSITORY_NAME_BACKEND}:/stats ./${REPOSITORY_NAME_BACKEND}
                                '''
                            }
                        }
                        stage('S3 cleanup and upload stats') {
                            steps {
                                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'profile-lientech-aws']]) {
                                    sh 'aws s3 rm s3://${BUCKET_NAME}/${REPOSITORY_NAME_BACKEND}/* --recursive'
                                    sh 'aws s3 cp ./${REPOSITORY_NAME_BACKEND} s3://${BUCKET_NAME}/${REPOSITORY_NAME_BACKEND} --recursive'
                                }
                            }
                        }
                    }
                }
                stage('chatbot') {
                    stages {
                        stage('Building chatbot image') {
                            steps {
                                sh '''docker build  --build-arg REPO=${REPOSITORY_PREFIX}/${REPOSITORY_NAME_CHATBOT} \
                                --build-arg REPO_NAME=${REPOSITORY_NAME_CHATBOT} --build-arg SSH_PRV_KEY="$(cat ${SSH_CREDENTIALS})" \
                                --build-arg BRANCH=develop . -t gitstats-image:${REPOSITORY_NAME_CHATBOT}
                                '''
                            }
                        }
                        stage('Copying stats from container') {
                            steps {
                                sh '''docker run --name ${REPOSITORY_NAME_CHATBOT} -d gitstats-image:${REPOSITORY_NAME_CHATBOT} tail -f /dev/null && \
                                mkdir -p ${REPOSITORY_NAME_CHATBOT} && docker cp ${REPOSITORY_NAME_CHATBOT}:/stats ./${REPOSITORY_NAME_CHATBOT}
                                '''
                            }
                        }
                        stage('S3 cleanup and upload stats') {
                            steps {
                                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'profile-lientech-aws']]) {
                                    sh 'aws s3 rm s3://${BUCKET_NAME}/${REPOSITORY_NAME_CHATBOT}/* --recursive'
                                    sh 'aws s3 cp ./${REPOSITORY_NAME_CHATBOT} s3://${BUCKET_NAME}/${REPOSITORY_NAME_CHATBOT} --recursive'
                                }
                            }
                        }
                    }
                }
                stage('classifier-service') {
                    stages {
                        stage('Building classifier-service image') {
                            steps {
                                sh '''docker build  --build-arg REPO=${REPOSITORY_PREFIX}/${REPOSITORY_NAME_CLASSIFIER} \
                                --build-arg REPO_NAME=${REPOSITORY_NAME_CLASSIFIER} --build-arg SSH_PRV_KEY="$(cat ${SSH_CREDENTIALS})" \
                                --build-arg BRANCH=develop . -t gitstats-image:${REPOSITORY_NAME_CLASSIFIER}
                                '''
                            }
                        }
                        stage('Copying stats from container') {
                            steps {
                                sh '''docker run --name ${REPOSITORY_NAME_CLASSIFIER} -d gitstats-image:${REPOSITORY_NAME_CLASSIFIER} tail -f /dev/null && \
                                mkdir -p ${REPOSITORY_NAME_CLASSIFIER} && docker cp ${REPOSITORY_NAME_CLASSIFIER}:/stats ./${REPOSITORY_NAME_CLASSIFIER}
                                '''
                            }
                        }
                        stage('S3 cleanup and upload stats') {
                            steps {
                                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'profile-lientech-aws']]) {
                                    sh 'aws s3 rm s3://${BUCKET_NAME}/${REPOSITORY_NAME_CLASSIFIER}/* --recursive'
                                    sh 'aws s3 cp ./${REPOSITORY_NAME_CLASSIFIER} s3://${BUCKET_NAME}/${REPOSITORY_NAME_CLASSIFIER} --recursive'
                                }
                            }
                        }
                    }
                }
                stage('candidate-ranking') {
                    stages {
                        stage('Building candidate-ranking image') {
                            steps {
                                sh '''docker build  --build-arg REPO=${REPOSITORY_PREFIX}/${REPOSITORY_NAME_RANKING} \
                                --build-arg REPO_NAME=${REPOSITORY_NAME_RANKING} --build-arg SSH_PRV_KEY="$(cat ${SSH_CREDENTIALS})" \
                                --build-arg BRANCH=develop . -t gitstats-image:${REPOSITORY_NAME_RANKING}
                                '''
                            }
                        }
                        stage('Copying stats from container') {
                            steps {
                                sh '''docker run --name ${REPOSITORY_NAME_RANKING} -d gitstats-image:${REPOSITORY_NAME_RANKING} tail -f /dev/null && \
                                mkdir -p ${REPOSITORY_NAME_RANKING} && docker cp ${REPOSITORY_NAME_RANKING}:/stats ./${REPOSITORY_NAME_RANKING}
                                '''
                            }
                        }
                        stage('S3 cleanup and upload stats') {
                            steps {
                                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'profile-lientech-aws']]) {
                                    sh 'aws s3 rm s3://${BUCKET_NAME}/${REPOSITORY_NAME_RANKING}/* --recursive'
                                    sh 'aws s3 cp ./${REPOSITORY_NAME_RANKING} s3://${BUCKET_NAME}/${REPOSITORY_NAME_RANKING} --recursive'
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    post {
        cleanup {
            sh '''
                docker container prune -f
                docker rm $(docker ps -aq) -f
                docker rmi $(docker images -aq) -f
                docker images
            '''
            dir("${WORKSPACE}@tmp") { deleteDir() }
            deleteDir()
        }
    }
}